apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/nginx.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
    paths:
    - path: /
      backend:
        serviceName: client-cluster-ip-service
        port: 3000
    - path: /api/
      backend:
        serviceName: server-cluster-ip-service
        port: 5000        